println("#######################################################################")
println("#")
println("#  root project is:           [" + project.name + "]")
println("#  detected os is:            [" + System.getProperty("os.name") + "]")
println("#  detected java home is:     [" + System.getProperty("java.home") + "]")
println("#  detected java version is:  [" + System.getProperty("java.version") + "]")
println("#  detected java vendor is:   [" + System.getProperty("java.vendor") + "]")
println("#  build version is:          [$version]")
println("#  starting task is:          " + project.gradle.startParameter.taskNames)
println("#")
println("#######################################################################")
println("\n")

val commonLang by extra("\"org.apache.commons\":\"commons-lang3\":\"3.0\"")